# Generated by Django 3.1.1 on 2020-09-30 16:43

from django.db import migrations, models
import django.db.models.deletion
import shopApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='images/Categories/<built-in function id>/')),
            ],
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Description', models.TextField()),
                ('Address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=128)),
                ('Description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=128)),
                ('Description', models.TextField()),
                ('Floor', models.PositiveIntegerField()),
                ('Phone', models.CharField(max_length=32)),
                ('Categories', models.ManyToManyField(to='shopApp.Category')),
                ('ShopCenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.center')),
            ],
        ),
        migrations.CreateModel(
            name='ShopImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shopApp.models.get_upload_image_filename)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='NewImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shopApp.models.get_upload_image_filename)),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.new')),
            ],
        ),
        migrations.CreateModel(
            name='CenterImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shopApp.models.get_upload_image_filename)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopApp.center')),
            ],
        ),
    ]
