# Generated by Django 3.1.1 on 2020-09-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_auto_20200930_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerimages',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopApp.center'),
        ),
        migrations.AlterField(
            model_name='newimages',
            name='new',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopApp.new'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='Categories',
            field=models.ManyToManyField(related_name='Categories', to='shopApp.Category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ShopCenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Center', to='shopApp.center'),
        ),
        migrations.AlterField(
            model_name='shopimages',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopApp.shop'),
        ),
    ]
