# Generated by Django 3.1.1 on 2020-09-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_auto_20200930_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='static/images/Categories/'),
        ),
    ]
